version: '3.8'
services:
  nhtsa-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: nhtsa
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nhtsa_db
    ports:
      - "5432:5432"